version: '3.9'

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"